<?php

namespace KitFriendBundle\Repository;

/**
 * MemberPartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberPartnerRepository extends \Doctrine\ORM\EntityRepository
{
}
