<?php

namespace KitFriendBundle\Repository;

/**
 * MemberInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
