memberpartner_index:
    path:     /
    defaults: { _controller: "KitFriendBundle:MemberPartner:index" }
    methods:  GET

memberpartner_show:
    path:     /{id}/show
    defaults: { _controller: "KitFriendBundle:MemberPartner:show" }
    methods:  GET

memberpartner_new:
    path:     /new
    defaults: { _controller: "KitFriendBundle:MemberPartner:new" }
    methods:  [GET, POST]

memberpartner_edit:
    path:     /{id}/edit
    defaults: { _controller: "KitFriendBundle:MemberPartner:edit" }
    methods:  [GET, POST]

memberpartner_delete:
    path:     /{id}/delete
    defaults: { _controller: "KitFriendBundle:MemberPartner:delete" }
    methods:  DELETE
